# Generated by Django 4.2 on 2024-02-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_payment_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_amount',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='id сессии оплаты'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='ссылка на оплату'),
        ),
    ]
