# Generated by Django 4.2 on 2024-02-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='link_video',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='ссылка на видео'),
        ),
    ]
