# Generated by Django 4.2 on 2024-02-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_course_owner_lesson_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='link_video',
            field=models.TextField(blank=True, null=True, unique=True, verbose_name='ссылка на видео'),
        ),
    ]
