# Generated by Django 4.2 on 2024-03-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_alter_lesson_link_video_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=1000, verbose_name='Стоимость курса'),
        ),
    ]
